### ISSUE TITLE
lc3_clean theme

### ISSUE THREAD

**Issue by smearedred** [litecommerce/lc3_clean#1]
I obviously do not know what i am doing, but I have looked everywhere and cannot figure out how to change the main page picture from the fruits_vegetables picture.

Also is there a way to put a slide show of pictures there instead?

Thank you

**Comment by maxmukhin** [comment]
> cannot figure out how to change the main page picture from the fruits_vegetables picture.

This information is changed on the "Root category" category modify page.

> Also is there a way to put a slide show of pictures there instead?

We have a partner company which has been developed the "Banner System" module for LC:

http://mods.x-cart.com/Banner-System.html

Some of LC installation already has this module. 

For example:  http://tools4boards.com/

You could contact this company and request a quote for this module.

Thank you for your cooperation.
